name: build & deploy docker image

on:
  push:
    branches:
    - TestAction

jobs:
  MainTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install Dependencies
        run: pip freeze > requirements.txt 